modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MairwunNx/RandomTeleport/issues"

[[mods]]
    modId="random_teleport"
    version="1.14.4-1.0.0"
    displayName="Random Teleport"
    authors="MairwunNx (Pavel Erokhin)"
    updateJSONURL="https://raw.githubusercontent.com/MairwunNx/RandomTeleport/FORGE-1.14.4/update.json"
    displayURL="https://github.com/MairwunNx/RandomTeleport"
    description='''
    Modification for minecraft allows you to teleport to a random location in the world.
    '''

[[dependencies.projectessentials]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
